swagger: "2.0"
info:
  description: ""
  version: "2.7.0"
  title: "Import External APIs"
host: "e8e2ae51-9105-45a8-951c-94b92386a272.mock.pstmn.io"
basePath: "/api/external"
tags:
- name: "report"
  description: "Report APIs"
  externalDocs:
    description: "Find out more"
    url: "https://www.izenda.com/"
- name: "dashboard"
  description: "Dashboard APIs"
  externalDocs:
    description: "Find out more"
    url: "https://www.izenda.com/"
- name: "file"
  description: "File APIs"
  externalDocs:
    description: "Find out more"
    url: "https://www.izenda.com/"
schemes:
- "http"
paths:
  /report/import:
    post:
      tags:
        - report
      summary: "Import the reports from specified fileIds"
      description: ""
      operationId: importReport
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: selected_tenant
          required: true
          description: "The id of the selected tenant"
          type: "string"
        - in: header
          name: access_token
          required: true
          type: "string"
          description: "The access token"
        - in: body
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/ImportReportRequest"
      responses:
        401:
          description: "You don't have permission to perform this action"
        400:
          description: "Bad Request"
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/ImportReportResponse"
            
  /dashboard/import:
    post:
      tags:
        - dashboard
      summary: "Import the dashboards from specified fileIds"
      description: ""
      operationId: importDashboard
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: selected_tenant
          required: true
          description: "The id of the selected tenant"
          type: "string"
        - in: header
          name: access_token
          required: true
          type: "string"
          description: "The access token"
        - in: body
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/ImportDashboardRequest"
      responses:
        401:
          description: "You don't have permission to perform this action"
        400:
          description: "Bad Request"
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/ImportDashboardResponse"
            
  /file:
    post:
      tags:
      - file
      summary: "Upload file"
      description: "Import the specified to server"
      operationId: "uploadFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
        - in: header
          name: selected_tenant
          required: true
          description: "The id of the selected tenant"
          type: "string"
        - in: header
          name: access_token
          required: true
          type: "string"
          description: "The access token"
        - name: "file"
          in: "formData"
          description: "The file to upload"
          required: false
          type: "file"
      responses:
        200:
          description: "OK"
          schema:
            type: "string"
            format: "<GUID>_<report/dashboard name>"
            example: "2dadb1ef-c40a-44e8-b8fc-e0a46535c781_Monthly Expenses"
            description: "The id of the successful imported file"
        401:
          description: "You don't have permission to perform this action"
        400:
          description: "Bad Request"
  /file/{fileId}:
    delete:
      tags:
      - file
      summary: "Delete file"
      description: "Delete specified from server"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: 
        - in: header
          name: selected_tenant
          required: true
          description: "The id of the selected tenant"
          type: "string"
        - in: header
          name: access_token
          required: true
          type: "string"
          description: "The access token"
        - in: path
          name: fileId
          required: true
          type: "string"
          format: "<GUID>_<report/dashboard name>"
          description: "The id of the file to delete"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        401:
          description: "You don't have permission to perform this action"
    
  
  
definitions:
  ImportReport:
    type: "object"
    properties:
      fileId:
        type: "string"
        description: "The file id"
        example: "2dadb1ef-c40a-44e8-b8fc-e0a46535c781_Monthly Expenses"
      reportName:
        type: "string"
        description: "The report name in destination"
        example: "Monthly Expenses"
      categoryName:
        type: "string"
        description: "The name of the category in destination"
        example: "Monthly Reports"
      subCategoryName:
        type: "string"
        description: "The name of the sub-category in destination"
        example: "March 2018"
      isGlobal:
        type: "boolean"
        description: "Whether the report is global or not in destination"
        default: false
        example: false
        
  ImportReportRequest:
    type: "object"
    properties:
      reports:
        type: "array"
        description: "An array of the following object"
        items:
          $ref: "#/definitions/ImportReport"
      overrideDuplicates:
        type: "boolean"
        description: "Whether overwritten duplicate reports or ignore"
        default: false
        example: true
      tenantId:
        type: "string"
        format: "GUID"
        description: "Specify the destination tenant's id (null for the System)"
        example: null
      databaseMapping:
        type: "array"
        description: "The array of database mappings"
        items:
          $ref: "#/definitions/DatabaseMapping"
      importSourceId:
        type: "boolean"
        description: "To keep all source report ids as the new report ids in destination"
        default: false
        example: true
      importAccessRight:
        type: "boolean"
        description: "Whether to import access rights or not. The request will fail if this field is not specified"
        default: false
        example: true
      importFilterValues:
        type: "boolean"
        description: "Whether to import filter values or not"
        default: false 
        example: true
      removeSourceFileAfterImport:
        type: "boolean"
        description: "Whether to remove file after import or not"
        default: false
        example: true
        
  ImportReportResponse:
    type: "array"
    description: "An array of the following objects"
    items:
      type: "object"
      properties:
        fileId:
          type: "string"
          format: "GUID"
          description: "The id of file"
          example: "2dadb1ef-c40a-44e8-b8fc-e0a46535c781_Monthly Expenses"
        reportId:
          type: "string"
          format: "GUID"
          description: "The id of report in destination"
          example: "7bbb5825-4226-4b81-830c-e8a175d62640"
        success: 
          type: "boolean"
          description: "Whether the report imported successful or not"
          example: true
        message:
          type: "string"
          description: "Error message if any"
  
  ImportDashboard:
    type: "object"
    properties:
      fileId:
        type: "string"
        description: "The file id"
        example: "2dadb1ef-c40a-44e8-b8fc-e0a46535c781_Monthly Expenses"
      dashboardName:
        type: "string"
        description: "The dashboard name in destination"
        example: "Monthly Expenses"
      categoryName:
        type: "string"
        description: "The name of the category in destination"
        example: "Monthly Reports"
      subCategoryName:
        type: "string"
        description: "The name of the sub-category in destination"
        example: "March 2018"
      isGlobal:
        type: "boolean"
        description: "Whether the report is global or not in destination"
        default: false
        example: false
        
  ImportDashboardRequest:
    type: "object"
    properties:
      dashboards:
        type: "array"
        description: "An array of the following objects"
        items:
          $ref: "#/definitions/ImportDashboard"
      overrideDuplicates:
        type: "boolean"
        description: "Whether overwritten duplicate dashboards or ignore"
        default: false
        example: true
      tenantId:
        type: "string"
        format: "GUID"
        description: "Specify the destination tenant’s id (null for the System)"
        example: null
      databaseMapping:
        type: "array"
        description: "The array of database mappings"
        items:
          $ref: "#/definitions/DatabaseMapping"
      importSourceId:
        type: "boolean"
        description: "To keep all source dashboard ids as destination dashboard ids"
        default: false
        example: true
      importAccessRight:
        type: "boolean"
        description: "Whether to import access rights or not"
        default: false
        example: true
      importFilterValues:
        type: "boolean"
        description: "Whether to import filter values or not"
        default: false
        example: true
      removeSourceFileAfterImport:
        type: "boolean"
        description: "Whether to remove file after import or not"
        default: false
        example: true
  
  ImportDashboardResponse:    
    type: "array"
    description: "An array of the following object"
    items:
      type: "object"
      properties:
        fileId:
          type: "string"
          format: "GUID"
          description: "The id of file"
          example: "2dadb1ef-c40a-44e8-b8fc-e0a46535c781_Monthly Expenses"
        dashboardId:
          type: "string"
          format: "GUID"
          description: "The id of dashboard in destination"
          example: "7bbb5825-4226-4b81-830c-e8a175d62640"
        success: 
          type: "boolean"
          description: "Whether the dashboard imported successful or not"
          example: true
        message:
          type: "string"
          description: "Error message if any" 
  DatabaseMapping:
    type: "object"
    properties:
      sourceDatabaseName:
        type: "string"
        description: "The name of the source database"
        example: "Northwind"
      sourceServerType:
        type: "string"
        description: "The source database server type"
        example: "MSSQL"
      sourceSchema:
        type: "string"
        description: "The source schema"
        example: "dbo"
      destDatabaseName:
        type: "string"
        description: "The alias name of the destination database"
        example: "Southwind"
      destSchema:
        type: "string"
        description: "The destination schema"
        example: "dbo1"
      
  
externalDocs:
  description: "Find out more about Izenda"
  url: "https://www.izenda.com"